#!/usr/bin/env ruby
# frozen_string_literal: true

# Auto-load dotenv if available (common in Rails projects)
begin
  require 'dotenv/load'
rescue LoadError
  # dotenv not available, skip
end

require 'app_store_connect'

AppStoreConnect::CLI.new(ARGV).run
